## testes de requisições

// criação de estudante e paciente

# POST http://localhost:3050/api/students/register
# Content-Type: application/json

# {
#   "name": "Teste Teste",
#   "email": "teste@teste.com",
#   "password": "senha123",
#   "area": "Psicologia"
# }


# POST http://localhost:3050/api/patients/register
# Content-Type: application/json

# {
#   "name": "Carlos Teste",
#   "email": "carlos30@teste.com",
#   "password": "senha123",
#   "condition": "Ansiedade"
# }


# // LOGIN
# POST http://localhost:3050/api/auth/login
# Content-Type: application/json

# {
#   "email": "carlos30@teste.com",
#   "password": "senha123",
#   "role": "patient"
# }




POST http://localhost:3050/api/appointments/schedule
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InBhdGllbnQiLCJpYXQiOjE3NDQyNTk2NDgsImV4cCI6MTc0NDI2MzI0OH0.z8AiitVjyAV1J87l5z20qu8MqzsK68vRRnkenibyrys
Content-Type: application/json

{
  "student_id": 2,
  "start_time": "2025-04-12T14:00:00Z",
  "end_time": "2025-04-12T15:00:00Z"
}








