## TESTES

# ## CADASTRO DE PACIENTE
# POST http://localhost:3050/users/register/patient
# Content-Type: application/json

# {
#   "name": "João Paciente",
#   "email": "joao@exemplo.com",
#   "password": "senha123"
# }

# ## LOGIN DE PACIENTE
# POST http://localhost:3050/auth/login
# Content-Type: application/json

# {
#   "email": "joao@exemplo.com",
#   "password": "senha123"
# }

# ## LOGIN DE ADMIN
# POST http://localhost:3050/auth/login
# Content-Type: application/json

# {
#   "email": "admin2@exemplo.com",
#   "password": "admin123"
# }


# ## CADASTRO ESTUDANTE POR ADMIN
# POST http://localhost:3050/users/register/student
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwibmFtZSI6IkFkbWluMiIsImlhdCI6MTc0ODk3ODEzOSwiZXhwIjoxNzQ5MDY0NTM5fQ.C8bJGZ_ivwD58bX_BhhPuWMQmRNg3Jbu1VoWlerjsCY
# Content-Type: application/json

# {
#   "name": "Maria saraiva",
#   "email": "maria3@exemplo.com",
#   "password": "senha123"
# }

# ## LOGIN ESTUDANTE
# POST http://localhost:3050/auth/login
# Content-Type: application/json

# {
#   "email": "maria@exemplo.com",
#   "password": "senha456"
# }

# ## DISPONIBILIZAR HORÁRIO DE ATENDIMENTO
# POST http://localhost:3050/api/availability
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InN0dWRlbnQiLCJuYW1lIjoiTWFyaWEgRXN0dWRhbnRlIiwiaWF0IjoxNzQ4OTY0NTMxLCJleHAiOjE3NDkwNTA5MzF9.q53A2WmuMLxBp4gt4JwIl1eb0iV4Bb-tQHjf6P3Zn5Q
# Content-Type: application/json

# {
#   "date": "2025-22-02",
#   "start_time": "09:00",
#   "end_time": "10:00"
# }

# ## FAZER AGENDAMENTO
# POST http://localhost:3050/api/appointments
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InBhdGllbnQiLCJuYW1lIjoiSm_Do28gUGFjaWVudGUiLCJpYXQiOjE3NDg5NzE0MjcsImV4cCI6MTc0OTA1NzgyN30.Euei7XaSaoW4H8dg2DH_esONXCoUlLMh5laE3tydvik
# Content-Type: application/json

# {
#   "student_id": 4,
#   "date": "2025-11-02",
#   "start_time": "09:00",
#   "end_time": "10:00"
# }
 