## testes de requisições

# POST http://localhost:3050/api/students/register
# Content-Type: application/json

# {
#   "name": "Teste Teste",
#   "email": "teste@teste.com",
#   "password": "senha123",
#   "area": "Psicologia"
# }


# POST http://localhost:3050/api/patients/register
# Content-Type: application/json

# {
#   "name": "Carlos Teste",
#   "email": "carlos30@teste.com",
#   "password": "senha123",
#   "condition": "Ansiedade"
# }


# // LOGIN
# POST http://localhost:3050/api/auth/login
# Content-Type: application/json

# {
#   "email": "carlos30@teste.com",
#   "password": "senha123",
#   "role": "patient"
# }




# POST http://localhost:3050/api/appointments/schedule
# Authorization: Bearer 
# Content-Type: application/json

# {
#   "student_id": 3,
#   "start_time": "2025-04-23T14:00:00Z",
#   "end_time": "2025-04-23T15:00:00Z"
# }

# GET http://localhost:3050/api/appointments/debug-controller
# Authorization: Bearer 

# POST http://localhost:3050/api/patients/register
# Content-Type: application/json

# {
#   "name": "Tokoku Navara",
#   "email": "tokoku@navara.com",
#   "password": "senha123",
#   "condition": "Desconforto"
# }

# POST http://localhost:3050/api/students/register
# Content-Type: application/json

# {
#   "name": "jorge mathias",
#   "email": "jorge@mathias.com",
#   "password": "senha123",
#   "area": "Psicologia"
# }

# POST http://localhost:3050/api/auth/login
# Content-Type: application/json

# {
#   "email": "tokoku@navara.com",
#   "password": "senha123",
#   "role": "patient"
# }

# POST http://localhost:3050/api/auth/login
# Content-Type: application/json

# {
#   "email": "tokoku@navara.com",
#   "password": "senha123",
#   "role": "patient"
# }




